### ISSUE TITLE
Cannot deserialize UnsignedByte using Serializer.deserialize

### ISSUE THREAD

**Issue by tobi390** [davidmoten/odata-client#164]
Serialized some Object retrieved by my odata client that contains :

`private UnsignedByte userDataPresent;`

using com.github.davidmoten.odata.client.Serializer.serializePrettyPrint.

JSON snippet:

`"UserDataPresent" : {
    "value" : 1
  },`

 After that tried to deserialize using Serializer.deserialize(String text, Class<? extends T> cls, ContextPath contextPath, boolean addKeysToContextPath) and got an Exception:

`com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of com.github.davidmoten.odata.client.edm.UnsignedByte (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [....
  "UserDataPresent" : {
    "value" : 1
  },
 ...] (through reference chain: com.somecompany.odata.entity.Order["UserDataPresent"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:402)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at com.github.davidmoten.odata.client.Serializer.deserialize(Serializer.java:85)
	... 3 more
`

Currently using version 0.1.58. 

Deserialization works in case JSON is changed to:

`"UserDataPresent" : 1,`

**Comment by davidmoten** [comment]
ok I'll have a look

**Comment by davidmoten** [comment]
I fixed the problem with PR #165. I'll build a release shortly.

**Comment by davidmoten** [comment]
0.1.60 is on Maven Central now with the fix.

**Comment by tobi390** [comment]
Tested with 0.1.60, works fine!
Thank you!

**Comment by davidmoten** [comment]
Beaut, good to hear. Thanks for the report!
