### ISSUE TITLE
Dynamics 365 CRM (Entity crmbaseentity has no keys)

### ISSUE THREAD

**Issue by sir-vince** [davidmoten/odata-client#45]
Hi,
I'm attempting to load a dynamics 365 (CRM) manifest but it contains multiple abstract EntityTypes without a key. Example: `<EntityType Name="crmbaseentity" Abstract="true" />` from which all other base types point to as BaseType:
eg. `<EntityType Name="account" BaseType="mscrm.crmbaseentity"><Key><PropertyRef Name="accountid" /></Key>...`

This results in:
`java.lang.IllegalStateException: Entity crmbaseentity has no keys!`

Full stack trace:
`
java.lang.IllegalStateException: Entity crmbaseentity has no keys!
	at com.github.davidmoten.odata.client.generator.model.EntityType.getFirstKey(EntityType.java:125)
	at com.github.davidmoten.odata.client.generator.Generator.fieldNames(Generator.java:1115)
	at com.github.davidmoten.odata.client.generator.Generator.writeEntity(Generator.java:540)
	at com.github.davidmoten.odata.client.generator.Generator.lambda$generate$5(Generator.java:163)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.github.davidmoten.odata.client.generator.Generator.generate(Generator.java:163)
	at com.github.davidmoten.odata.client.generator.GeneratorTest.testGenerateDynamics365(GeneratorTest.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)`

**Comment by sir-vince** [comment]
After adding a conditional check in Generator.java like this:
`if ( ! t.isAbstract()) {
				p.format("%s}\n", indent.left());
				String nullCheck = fieldNames(t) //
						.stream() //
						.map(f -> f + " != null") //
						.collect(Collectors.joining(" && "));
				if (!nullCheck.isEmpty()) {
					nullCheck = " && " + nullCheck;
				}
				p.format("\n%s@%s\n", indent, imports.add(Override.class));
				p.format("%spublic void postInject(boolean addKeysToContextPath) {\n", indent);
				p.format("%sif (addKeysToContextPath%s) {\n", indent.right(), nullCheck);
				p.format("%scontextPath = contextPath.clearQueries()%s;\n", indent.right(), getAddKeys(t, imports));
				p.format("%s}\n", indent.left());
				p.format("%s}\n", indent.left());
			}`

I'm getting another error:
`java.lang.IllegalStateException: Entity expando has no keys!

	at com.github.davidmoten.odata.client.generator.model.EntityType.getFirstKey(EntityType.java:125)
	at com.github.davidmoten.odata.client.generator.Generator.fieldNames(Generator.java:1118)
	at com.github.davidmoten.odata.client.generator.Generator.writeEntity(Generator.java:542)
	at com.github.davidmoten.odata.client.generator.Generator.lambda$generate$5(Generator.java:163)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.github.davidmoten.odata.client.generator.Generator.generate(Generator.java:163)
	at com.github.davidmoten.odata.client.generator.GeneratorTest.testGenerateDynamics365(GeneratorTest.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
`

which is based on `<EntityType Name="expando" BaseType="mscrm.crmbaseentity" OpenType="true" />` in the manifest.

**Comment by davidmoten** [comment]
thanks for the report, should be easy to fix, I'll check it out.

**Comment by davidmoten** [comment]
BTW, would you be able to submit your metadata here for my interest? Feel free to remove your orgs customizations of course.

**Comment by davidmoten** [comment]
I've added support for abstract EntityTypes without keys to master branch. I'll release shortly but feel free to try master yourself.

**Comment by davidmoten** [comment]
0.1.34 is on Maven Central now with the fix.

**Comment by sir-vince** [comment]
That is awesome reaction time :) I tested it but I'm still getting the error:
```
java.lang.IllegalStateException: Entity expando has no keys!
	at com.github.davidmoten.odata.client.generator.GeneratorTest.testGenerateDynamics365(GeneratorTest.java:94)
```

I have added an example metadata.xml from a test environment so it contains a few custom entities but a clean version can be extracted if it is preferred.

[dynamics-365-metadata.xml.zip](https://github.com/davidmoten/odata-client/files/5151652/dynamics-365-metadata.xml.zip)

**Comment by davidmoten** [comment]
Hi, two problems:

One is that the `expando` EntityType does not comply with the OData specification which says that every EntityType should have at least one key (http://docs.oasis-open.org/odata/odata/v4.01/csprd01/part3-csdl/odata-v4.01-csprd01-part3-csdl.html#_Toc469935971). Just delete that line from the metadata before generating. I currently automate a few fixups like this on the MsGraph v1.0 and beta metadata before generating.

The other problem is that the metadata you gave me (thanks!) has Reference elements to other metadata files:

```xml
<edmx:Reference Uri="http://vocabularies.odata.org/OData.Community.Keys.V1.xml">
    <edmx:Include Namespace="OData.Community.Keys.V1" Alias="Keys"/>
    <edmx:IncludeAnnotations TermNamespace="OData.Community.Keys.V1"/>
  </edmx:Reference>
  <edmx:Reference Uri="http://vocabularies.odata.org/OData.Community.Display.V1.xml">
    <edmx:Include Namespace="OData.Community.Display.V1" Alias="Display"/>
    <edmx:IncludeAnnotations TermNamespace="OData.Community.Display.V1"/>
  </edmx:Reference>
```
This is the first time I've come across Reference being used and I'm happy to have a look at it. Can you provide me with the full set of Referenced metadata as well?

BTW what url did you use to get the dynamics metadata?

**Comment by davidmoten** [comment]
Ah I see those references are from https://github.com/OData/vocabularies and are not Microsoft controlled. I'll have a look.

**Comment by sir-vince** [comment]
Thank you for taking a look at this issue :) If it can become functional, I think this will be the only generator for java that can work with metadata from dynamics :) 

The data is retrieved from https://_solution_.api.crm4.dynamics.com/api/data/v9.1/$metadata but it is always hidden behind authentication. The file provided is a raw dump from that URL.

**Comment by davidmoten** [comment]
Righto, the metadata is generating fine. I've added a module *odata-client-microsoft-dynamics* to this project that generates code from the metadata you gave me. To get the generation working I had to do some enhancements to handle naming conflicts but also I had to change the metadata as per this diff: https://github.com/davidmoten/odata-client/compare/c587d29..c094e7a#diff-e8955361052bd8090adea03ccb4e3d6e. In short I

* removed EntityType that had no key (*expando*)
* worked around a signature conflict that looks like a bug with the metadata
* the EntitySet *owners* is missing

I've raised an issue on Dynamics CRM forums to query the missing EntitySet *owners*: https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/400273/missing-entityset-owners-in-dynamics-crm-odata-metadata-xml-v9-1.

**Comment by sir-vince** [comment]
I'm not so experienced with authenticating against Graph API but I would expect it to be very close. I'm currently using "Client Credentials":
```
curl --location --request POST 'https://login.microsoftonline.com/_TENANT_ID_/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=_CLIENT_ID_' \
--data-urlencode 'client_secret=_SECRET_' \
--data-urlencode 'resource=https://_SOLUTION_.crm4.dynamics.com/'
```
I have been attempting to get it working with their v2 of azure ad but they removed the "resource" parameter and I'm unable to create a valid token using the new "scope" parameter which is why I'm using v1 in this example.

Regarding generating a client for dynamics, generally it will be necessary for everyone to generate their own client as it also contains their customizations to the system so maybe the diff you linked could be added to a readme as an example of how it should be modified to be compatible.

**Comment by davidmoten** [comment]
Thanks, the client will be reusable across people's customized generated code. I've already done this for https://github.com/davidmoten/odata-client/tree/master/odata-client-microsoft-analytics. I'll build a client for you to try.

**Comment by davidmoten** [comment]
Try this code. It uses oauth2 with client credentials:

https://github.com/davidmoten/odata-client/blob/master/odata-client-microsoft-dynamics/src/test/java/com/github/davidmoten/ms/dynamics/DynamicsMain.java

It uses a class called Analytics, I'll refactor it once we've got it working. See how you pass in your generated container class to the builder? That's how the custom client is made.

**Comment by davidmoten** [comment]
Need any help doing the test?

**Comment by sir-vince** [comment]
Hi, sorry for the delay. I got overwhelmed by work :( 
The build completed successful but when running DynamicsMain.java I'm getting the following error:
```
Exception in thread "main" com.github.davidmoten.odata.client.ClientException: responseCode=401 from url=https://orgb00c40eb.api.crm4.dynamics.com/api/data/v9.1/accounts, expectedResponseCode in [200, 299], message=

	at com.github.davidmoten.odata.client.internal.RequestHelper.checkResponseCode(RequestHelper.java:88)
	at com.github.davidmoten.odata.client.internal.RequestHelper.checkResponseCode(RequestHelper.java:94)
	at com.github.davidmoten.odata.client.CollectionPageEntityRequest.get(CollectionPageEntityRequest.java:36)
	at com.github.davidmoten.odata.client.CollectionEntityRequestOptionsBuilder.get(CollectionEntityRequestOptionsBuilder.java:178)
	at com.github.davidmoten.odata.client.CollectionEntityRequestOptionsBuilder.stream(CollectionEntityRequestOptionsBuilder.java:187)
	at com.github.davidmoten.ms.dynamics.DynamicsMain.main(DynamicsMain.java:27)
```

I checked the JWT being sent out and it seems the "aud" is configured to "https://graph.microsoft.com" where it should be "https://_SOLUTION_.crm4.dynamics.com". 

Digging further in, I found in `ClientCredentialsAccessTokenProvider` it is setting the "resource" as a constant based on `ClientCredentialsAccessTokenProvider.RESOURCE_MS_GRAPH`. I changed the constant to `https://_SOLUTION_.crm4.dynamics.com` and after a rebuild, I successfully extracted data from my dynamics solution. 

To complete this one, I think if we can set configure the "resource" parameter from the builder like this it would solve the issue:
```
        System client = Dynamics //
                .service(System.class) //
                .baseUrl("https://_SOLUTION_.api.crm4.dynamics.com/api/data/v9.1/") //
                .tenantName("TENANT_ID") //
                .clientId("CLIENT_ID") //
                .clientSecret("SECRET") //
                .resource("https://_SOLUTION_.api.crm4.dynamics.com")
                .refreshBeforeExpiry(5, TimeUnit.MINUTES) //
                .build();
```

**Comment by davidmoten** [comment]
Well done, that's great. I'll sort it out shortly.

**Comment by davidmoten** [comment]
So you didn't change the scope value (which is Graph specific in the builder at the moment)?

**Comment by davidmoten** [comment]
I've done quite a bit of rejigging of builders. Try DynamicsMain again:

https://github.com/davidmoten/odata-client/blob/master/odata-client-microsoft-dynamics/src/test/java/com/github/davidmoten/ms/dynamics/DynamicsMain.java

**Comment by sir-vince** [comment]
Regarding the scope parameter, I attempted removing it and everything still seems to work, I'm not sure it is required in this instance. 

I just pulled the latest master and it worked immediately :) With these changes, I think we can close down the issue. 

I will start implementing some of the scenarios I need to confirm everything works as expected and if I run into some issues, we can handle that in separate issues. 

Virtual highfive !!! 🥇

**Comment by davidmoten** [comment]
I've made scope optional (that's reflected in DynamicsMain now) and released 0.1.36 to Maven Central with all these changes.

Re scope, I notice that other oauth2 flows (like GitHub) relate an empty scope to read-only authorization so you might want to test if update is supported by the client when no scope is specified. 

Do you have other (earlier or later versions) metadata for the CRM service? I'd like to see one that has the EntitySet owners defined.

**Comment by davidmoten** [comment]
Got no response from Dynamics forums about the broken metadata (EntitySet owners not present). I obtained my organisation's Dynamics CRM metadata and it suffered from the same problem even though it was crm6 not crm4. I opened a stackoverflow post in another attempt to get an answer.

https://stackoverflow.com/questions/63984862/why-is-the-entityset-owners-not-present-in-dynamics-crm-metadata

**Comment by davidmoten** [comment]
Closing as the original issue and follow up have been addressed. Incomplete Dynamics metadata can be talked about in a fresh issue if anyone wants to continue the conversation.

**Comment by gordonjohnston72** [comment]
> Facing an error while runnig the pipline ({"error":{"code":"0x80040216","message":"Custom state is not set for entity type crmbaseentity."}}) can any one guide me.

Did you get a solutionfor this?  I am deploying through the pipleine and have bever seen this error before.

**Comment by davidmoten** [comment]
Thanks for reporting back on the solution. That's a nasty business to try and debug, you did well!
